### ISSUE TITLE
奇怪,提示/Lofter数据/首页－关注: No such file or directory

### ISSUE THREAD

**Issue by zhoupIT** [EliseTonight/LOFTER-OC#1]
你好，感谢你的反馈。目前已经修复了，是复制file的时候没有选择copy，仅仅引用了一下。这个LOFTER目前还是雏形，我会逐步完善的，谢谢。

**Comment by EliseTonight** [comment]
你好，感谢你的反馈。目前已经修复了，是复制file的时候没有选择copy，仅仅引用了一下。这个LOFTER目前还是雏形，我会逐步完善的，谢谢。

**Comment by EliseTonight** [comment]
你好，感谢你的反馈。bug目前已经修复了，是复制file的时候没有选择copy，仅仅reference。这个LOFTER项目目前还是雏形，我会逐步完善的，谢谢。
